POST {{api_url}}/auth/register
Content-Type: application/json

{
    "email": "nak110@gmail.com",
    "username": "nak110",
    "password": "password",
    "role": "admin"
}

###
POST {{api_url}}/auth/login
Content-Type: application/json

{
    "username": "nak110",
    "password": "password"
}