POST {{api_url}}/auth/register
Content-Type: application/json

{
    "email": "william@gmail.com",
    "username": "william678",
    "password": "password"
}

###
POST {{api_url}}/auth/login
Content-Type: application/json

{
    "username": "nak110",
    "password": "password"
}