POST {{api_url}}/auth/register
Content-Type: application/json

{
    "email": "jack123@gmail.com",
    "username": "jack123",
    "password": "password",

}

###
POST {{api_url}}/auth/login
Content-Type: application/json

{
    "username": "nak110",
    "password": "password"
}