GET {{api_url}}/recipes
Content-Type: application/json
Authorization: Bearer {{admin_token}}

###
GET {{api_url}}/recipes/4
Content-Type: application/json
Authorization: Bearer {{user_token}}

###
POST {{api_url}}/recipes
Content-Type: application/json
Authorization: Bearer {{user_token}}

{
    "name": "Fried Rice",
    "ingredients": "Rice, Egg, Carrot, Peas, Soy Sauce",
    "instructions": "Cook rice. Scramble eggs. Mix all ingredients in a pan and stir-fry with soy sauce."
}

###
PUT {{api_url}}/recipes/4
Content-Type: application/json
Authorization: Bearer {{user_token}}

{
    "name": "Fried Rice",
    "ingredients": "Rice, Egg2, Carrot, Peas, Soy Sauce",
    "instructions": "Cook rice. Scramble eggs. Mix all ingredients in a pan and stir-fry with soy sauce."
}

###
DELETE {{api_url}}/recipes/11
Content-Type: application/json
Authorization: Bearer {{user_token}}
